version: "1"
services:
  postgres:
    image: postgres
    container_name: buryson_db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=buryson_db
      - POSTGRES_USER=postgres
    volumes:
      - /Users/carlos.jaldin/data/db:/var/lib/postgresql/data
networks:
    default:
        driver: bridge
    